#Minecraft server properties
#Wed Apr 22 04:17:06 CEST 2026
accepts-transfers=false
allow-flight=true
allow-nether=true
broadcast-console-to-ops=false
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=normal
enable-code-of-conduct=false
enable-command-block=true
enable-jmx-monitoring=false
enable-query=true
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=true
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=-3279809536187412499
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=xD5ImvnQCAEfnAVXkL8NAsjqNjqTIkT21z4C34b8
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=50
max-tick-time=60000
max-world-size=29999984
motd=§6✦ §2Explorer's Eden §7| §6Vanilla+ §7| §9Claims §7| §cCasual
network-compression-threshold=256
online-mode=true
op-permission-level=4
pause-when-empty-seconds=300
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=true
resource-pack=https://github.com/Explorers-Eden/Explorers-Eden-Resources/releases/download/resource-pack-latest/explorers-eden-resources.zip
resource-pack-id=
resource-pack-prompt={"color"\:"white","text"\:"We want everyone to have the same experience here, so you’ll need to use the resource pack. Just hit accept to keep going\!"}
resource-pack-sha1=1717fa151b92b4621b68d7a9711564385fc06d64
server-ip=0.0.0.0
server-port=25569
simulation-distance=5
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
status-heartbeat-interval=0
sync-chunk-writes=false
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=10
white-list=false
